version: "2"

networks:
  mimir: { name: mimir }
  minio: { name: minio, external: true }

services:
  mimir:
    container_name: "mimir"
    image: grafana/mimir:2.10.5
    restart: unless-stopped
    command:
      - -config.file=/etc/mimir.yaml
      - -target=all
      - -config.expand-env=true
    labels:
      de.pixelplastic.deduplication-key-filter: "mimir;mimir;8080;0.0.0.0"
    environment:
      MIMIR_S3_ENDPOINT: "minio:9000"
      MIMIR_S3_ACCESS_KEY_ID: "root"
      MIMIR_S3_SECRET_ACCESS_KEY: "secret1234"
    networks:
      - mimir
      - minio
    ports:
      - "8080:8080"
      - "9095:9095"
    volumes:
      - "./mimir.yaml:/etc/mimir.yaml:ro"
