version: "2"

networks:
  grafana-agent: { name: grafana-agent }
  cadvisor: { name: cadvisor, external: true }
  loki: { name: loki, external: true }
  mimir: { name: mimir, external: true }

services:
  grafana-agent:
    container_name: "grafana-agent"
    restart: unless-stopped
    image: grafana/agent:v0.38.1
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/config
    labels:
      de.pixelplastic.deduplication-key-filter: "grafana-agent;grafana-agent;12345;0.0.0.0"
    environment:
      AGENT_MODE: flow
    networks:
      - grafana-agent
      - cadvisor
      - loki
      - mimir
    ports:
      - "12345:12345"
    volumes:
      - "./config:/etc/agent/config:ro"
      # for discovery.docker (for loki)
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "/run/containerd/containerd.sock:/run/containerd/containerd.sock:ro"
