version: "2"

networks:
  node-exporter: { name: node-exporter }

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: "node-exporter"
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    labels:
      de.pixelplastic.deduplication-key-filter: "node-exporter;node-exporter;9100;0.0.0.0"
    # network_mode: host
    networks:
      - node-exporter
    ports:
      - "9100:9100"
    pid: host
    volumes:
      - '/:/host:ro,rslave'
